#!/usr/bin/env python3
"""
nodes/n00_inbox.py — Sovereign Intelligence System | Node 0.5
Inbox processor: classify, route, and convert user-dropped vault notes.

Routes:
  TRADE_IDEA         → 01-Trading/inbox_trades/
  LORE_AETHER        → 03-Universes/Age-of-Aether/inbox_expansions/
  LORE_EXPANSION     → Data/lore_general/
  THESIS_UPDATE      → 04-Intelligence/weekly_thesis.md  (append-only)
  MARKET_OBSERVATION → 02-Market-Intel/inbox_observations/
  UNKNOWN            → 00-Inbox/unrouted/

Usage:
    python nodes/n00_inbox.py
    alias: inbox
"""

import json
import logging
import shutil
from datetime import datetime
from pathlib import Path

import requests

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.config import VAULT_ROOT, INBOX_DIR, LOGS_DIR
from core.constants import OLLAMA_URL as OLLAMA_GENERATE, MODEL_FALLBACK

# ── Route targets ─────────────────────────────────────────────────────────────
ROUTES = {
    "TRADE_IDEA":         VAULT_ROOT / "01-Trading" / "inbox_trades",
    "LORE_EXPANSION":     VAULT_ROOT / "Data" / "lore_general",
    "LORE_AETHER":        VAULT_ROOT / "03-Universes" / "Age-of-Aether" / "inbox_expansions",
    "THESIS_UPDATE":      VAULT_ROOT / "04-Intelligence" / "weekly_thesis.md",  # append-only
    "MARKET_OBSERVATION": VAULT_ROOT / "02-Market-Intel" / "inbox_observations",
    "UNKNOWN":            INBOX_DIR / "unrouted",
    "SYSTEM_NOTE":        INBOX_DIR / "unrouted",
}

# Mapping from route label to RAG doc_type written into frontmatter
LABEL_DOC_TYPE = {
    "TRADE_IDEA":         "market_brief",
    "LORE_EXPANSION":     "lore",
    "LORE_AETHER":        "lore",
    "THESIS_UPDATE":      "weekly",
    "MARKET_OBSERVATION": "market_brief",
    "UNKNOWN":            "inbox",
    "SYSTEM_NOTE":        "inbox",
}

# Files generated by the pipeline — never touch these
SKIP_PREFIXES = (
    "Ignition_", "SocialContent_", "Expansion_", "Brief_",
    "Sovereign_Brief_", "Intraday_", "Weekly_", "Plays_", "Dashboard_",
)
SKIP_FILES = {"inbox_processor.py", ".DS_Store"}

# ── Tag-based fast routing (no LLM call) ─────────────────────────────────────
TAG_ROUTES = {
    "#intel":     "MARKET_OBSERVATION",
    "#soverign":  "MARKET_OBSERVATION",
    "#sovereign": "MARKET_OBSERVATION",
    "#market":    "MARKET_OBSERVATION",
    "#trade":     "TRADE_IDEA",
    "#lore":      "LORE_EXPANSION",
    "#aether":    "LORE_AETHER",
    "#creative":  "LORE_EXPANSION",
    "#thesis":    "THESIS_UPDATE",
    "#system":    "SYSTEM_NOTE",
}

# ── LLM classification prompt ─────────────────────────────────────────────────
_CLASSIFY_PROMPT = """You are a routing classifier for a personal intelligence system. Read the note below and output EXACTLY ONE of these labels, nothing else — no explanation, no punctuation, just the label:

TRADE_IDEA
LORE_EXPANSION
THESIS_UPDATE
MARKET_OBSERVATION
UNKNOWN

Rules:
- TRADE_IDEA: mentions a specific ticker, entry, stop, target, or trade setup
- LORE_EXPANSION: creative writing, story beats, character notes, world-building
- THESIS_UPDATE: market outlook, macro view, sector thesis, investment framework
- MARKET_OBSERVATION: price action, market structure, sector move, economic data point
- UNKNOWN: anything that doesn't clearly fit the above

Note:
{content}

Label:"""

# ── Logging ───────────────────────────────────────────────────────────────────
LOGS_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=LOGS_DIR / "sovereign_daily.log",
    level=logging.INFO,
    format="%(asctime)s [Node 0.5] %(message)s",
    datefmt="%Y-%m-%d %H:%M",
)

def _log(msg: str) -> None:
    print(f"  [Node 0.5] {msg}")
    logging.info(msg)


# ── Classification ────────────────────────────────────────────────────────────

def tag_route(content: str) -> str | None:
    """Check for explicit #tags before hitting the LLM. Returns label or None."""
    lower = content.lower()
    for tag, label in TAG_ROUTES.items():
        if tag in lower:
            return label
    return None


def classify_with_llm(content: str) -> str:
    """Call mistral:7b to classify the note. Returns a route label."""
    prompt = _CLASSIFY_PROMPT.format(content=content[:2000])
    try:
        resp = requests.post(
            OLLAMA_GENERATE,
            json={
                "model":   MODEL_FALLBACK,
                "prompt":  prompt,
                "stream":  False,
                "options": {"temperature": 0.0, "num_predict": 10},
            },
            timeout=30,
        )
        resp.raise_for_status()
        raw   = resp.json().get("response", "").strip().upper()
        label = raw.split()[0].rstrip(".:,") if raw else "UNKNOWN"
        if label in ROUTES:
            return label
        _log(f"Unexpected label '{label}' — routing to UNKNOWN")
        return "UNKNOWN"
    except Exception as e:
        _log(f"Classifier error: {e} — routing to UNKNOWN")
        return "UNKNOWN"


# ── File utilities ────────────────────────────────────────────────────────────

def _should_skip(filename: str) -> bool:
    return filename in SKIP_FILES or any(filename.startswith(p) for p in SKIP_PREFIXES)


def _unique_dest(dest_dir: Path, name: str, suffix: str) -> Path:
    """Return dest_dir/name.suffix, adding a timestamp if file already exists."""
    dest = dest_dir / f"{name}{suffix}"
    if dest.exists():
        dest = dest_dir / f"{name}_{datetime.now().strftime('%H%M%S')}{suffix}"
    return dest


def _convert_txt_to_md(filepath: Path, label: str, content: str, dest_dir: Path) -> Path:
    """Convert .txt inbox note to .md with RAG frontmatter. Removes original."""
    doc_type  = LABEL_DOC_TYPE.get(label, "inbox")
    dest_path = _unique_dest(dest_dir, filepath.stem, ".md")
    dest_path.write_text(
        f"---\n"
        f"date: {datetime.now().strftime('%Y-%m-%dT%H:%M:%S')}\n"
        f"type: inbox_routed\n"
        f"doc_type: {doc_type}\n"
        f"source: {filepath.name}\n"
        f"---\n\n{content}\n",
        encoding="utf-8",
    )
    filepath.unlink()
    return dest_path


# ── Core processor ────────────────────────────────────────────────────────────

def get_inbox_files() -> list[Path]:
    """Return .md and .txt files in 00-Inbox root only (no subdirectory recursion)."""
    return sorted(
        f for f in INBOX_DIR.iterdir()
        if f.is_file() and f.suffix in (".md", ".txt") and not _should_skip(f.name)
    )


def process_file(filepath: Path) -> dict:
    """Classify and route a single inbox file. Returns a result summary dict."""
    content = filepath.read_text(encoding="utf-8").strip()
    if not content:
        _log(f"SKIP (empty): {filepath.name}")
        return {"file": filepath.name, "label": "SKIP", "destination": None}

    label = tag_route(content) or classify_with_llm(content)

    # THESIS_UPDATE: append to weekly_thesis.md, no staging folder
    if label == "THESIS_UPDATE":
        thesis_path = VAULT_ROOT / "04-Intelligence" / "weekly_thesis.md"
        timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M")
        with thesis_path.open("a", encoding="utf-8") as f:
            f.write(f"\n\n---\n<!-- inbox: {filepath.name} @ {timestamp} -->\n{content}\n")
        filepath.unlink()
        _log(f"THESIS_UPDATE: {filepath.name} → appended to weekly_thesis.md")
        return {
            "file":        filepath.name,
            "label":       label,
            "destination": "04-Intelligence/weekly_thesis.md (appended)",
        }

    dest_dir = ROUTES[label]
    dest_dir.mkdir(parents=True, exist_ok=True)

    if filepath.suffix == ".txt":
        dest_path = _convert_txt_to_md(filepath, label, content, dest_dir)
        _log(f"{label}: {filepath.name} → {dest_path.relative_to(VAULT_ROOT)} [converted]")
    else:
        dest_path = _unique_dest(dest_dir, filepath.stem, filepath.suffix)
        shutil.move(str(filepath), str(dest_path))
        _log(f"{label}: {filepath.name} → {dest_path.relative_to(VAULT_ROOT)}")

    return {
        "file":        filepath.name,
        "label":       label,
        "destination": str(dest_path.relative_to(VAULT_ROOT)),
    }


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    print()
    print("  NODE 0.5 — INBOX PROCESSOR")
    print(f"  {datetime.now().strftime('%Y-%m-%d_%H%M')}")
    print("─" * 50)

    files = get_inbox_files()
    if not files:
        print("  [Node 0.5] Inbox clean — nothing to process.")
        _log("Inbox clean — 0 files processed.")
        print()
        return

    print(f"  [Node 0.5] Found {len(files)} file(s) to process...")
    print()

    results = [process_file(f) for f in files]

    counts: dict[str, int] = {}
    for r in results:
        counts[r["label"]] = counts.get(r["label"], 0) + 1

    print()
    print("─" * 50)
    print(f"  ✅ Processed {len(results)} file(s):")
    for label, count in sorted(counts.items()):
        print(f"     {label}: {count}")
    if counts.get("UNKNOWN"):
        print(f"  ⚠️  {counts['UNKNOWN']} file(s) unrouted — check 00-Inbox/unrouted/")

    _log(f"Complete — {len(results)} processed: {counts}")
    print()


if __name__ == "__main__":
    main()
