#!/usr/bin/env python3
"""
tools/patch_writer.py — Session B Patch Writer

Reads latest .issues.json from System-Reviews/.
Triages by issue_type:
  code_patch / prompt_patch  → Python heredoc patch script via qwen2.5-coder:14b
  config_change              → Markdown note with file context
  operator_decision          → Logged in summary only

Output: Scripts/patches/YYYY-MM-DD_HHMM/
  patch_NN_<type>_<slug>.py
  config_NN_<slug>.md
  _summary.md

Usage:
  python3 tools/patch_writer.py
  python3 tools/patch_writer.py --file path/to/specific.issues.json
  python3 tools/patch_writer.py --dry-run
"""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import json
import argparse
import re
import subprocess
from datetime import datetime
from pathlib import Path

from core.config import VAULT_ROOT

REVIEWS_DIR = VAULT_ROOT / "04-Intelligence" / "System-Reviews"
SCRIPTS_DIR  = Path(__file__).resolve().parent.parent
PATCHES_DIR  = SCRIPTS_DIR / "patches"
MODEL        = "qwen2.5-coder:14b"
CONTEXT_LINES = 50


def latest_issues_file() -> Path:
    files = sorted(REVIEWS_DIR.glob("*.issues.json"))
    if not files:
        raise FileNotFoundError(f"No .issues.json files found in {REVIEWS_DIR}")
    return files[-1]


def extract_file_context(node: str, section: str) -> str:
    """Return ~CONTEXT_LINES lines from node file anchored to section keyword."""
    node_path = SCRIPTS_DIR / node
    if not node_path.exists():
        return f"[FILE NOT FOUND: {node_path}]"
    try:
        lines = node_path.read_text(encoding="utf-8").splitlines()
    except OSError as e:
        return f"[READ ERROR: {e}]"

    anchor = 0
    section_clean = section.strip().lower()
    for i, line in enumerate(lines):
        if section_clean not in ("unknown", "") and section_clean in line.lower():
            anchor = i
            break
    else:
        for i, line in enumerate(lines):
            if line.startswith("def ") or line.startswith("class "):
                anchor = i
                break

    start = max(0, anchor - 5)
    end   = min(len(lines), anchor + CONTEXT_LINES)
    excerpt = "\n".join(f"{start+j+1:>4}  {l}" for j, l in enumerate(lines[start:end]))
    return f"# {node}  (lines {start+1}–{end})\n{excerpt}"


def call_qwen(prompt: str) -> str:
    result = subprocess.run(
        ["ollama", "run", MODEL],
        input=prompt, capture_output=True, text=True, timeout=180
    )
    if result.returncode != 0:
        return f"[QWEN ERROR: {result.stderr.strip()}]"
    return result.stdout.strip()


def slugify(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", text.lower())[:40].strip("_")


def generate_patch_script(issue: dict, context: str, out_dir: Path, idx: int) -> Path:
    prompt = f"""You are a surgical Python patch writer. Generate a safe, minimal patch script for the issue below.

ISSUE:
  Title:            {issue.get("issue")}
  Type:             {issue.get("issue_type")}
  Node:             {issue.get("node")}
  Section:          {issue.get("section")}
  Evidence:         {issue.get("evidence")}
  Suggested Change: {issue.get("suggested_change", "not specified")}

FILE CONTEXT:
{context}

RULES:
1. Output ONLY a complete runnable Python script. No explanation, no markdown fences.
2. The script must:
   a. Read the target file at its absolute path under /Users/cotyiwata/sovereign/Scripts/
   b. Define old with the exact string to replace (must be unique in the file)
   c. Assert old in src — abort with a clear message if not found
   d. Define new with the replacement
   e. Write the file back
   f. Print a one-line confirmation
3. For prompt_patch: target the prompt string inside the Python file.
4. Keep changes minimal — only touch what the suggested change describes.
5. First line: # AUTO-GENERATED by patch_writer.py — REVIEW BEFORE RUNNING
"""
    response = call_qwen(prompt)
    slug = slugify(issue.get("issue", f"issue_{idx}"))
    out_path = out_dir / f"patch_{idx:02d}_{issue.get('issue_type','unknown')}_{slug}.py"
    out_path.write_text(response, encoding="utf-8")
    return out_path


def generate_config_note(issue: dict, context: str, out_dir: Path, idx: int) -> Path:
    slug = slugify(issue.get("issue", f"issue_{idx}"))
    out_path = out_dir / f"config_{idx:02d}_{slug}.md"
    out_path.write_text(
        f"# CONFIG CHANGE — {issue.get('issue')}\n\n"
        f"**Node:** {issue.get('node')}\n"
        f"**Section:** {issue.get('section')}\n"
        f"**Evidence:** {issue.get('evidence')}\n"
        f"**Suggested Change:** {issue.get('suggested_change', 'not specified')}\n\n"
        f"## File Context\n```python\n{context}\n```\n\n"
        f"## Action\nReview the context above and manually update the relevant constant or threshold.\n",
        encoding="utf-8"
    )
    return out_path


def build_summary(issues: list, results: list, source: Path, out_dir: Path) -> Path:
    rows = "\n".join(
        f"| {iss.get('issue_type','?'):20s} | {iss.get('severity','?'):18s} "
        f"| {iss.get('node','?'):35s} | {res} |"
        for iss, res in zip(issues, results)
    )
    op_items = [i for i in issues if i.get("issue_type") == "operator_decision"]
    op_block = "\n".join(
        f"- **{i.get('issue')}** ({i.get('node')}): {i.get('suggested_change','')}"
        for i in op_items
    ) or "_None this run._"

    md = (
        f"# Patch Writer Summary\n"
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n"
        f"**Source:** {source.name}\n\n"
        f"| Type                 | Severity           | Node                                | Output |\n"
        f"|----------------------|--------------------|-------------------------------------|--------|\n"
        f"{rows}\n\n"
        f"## Operator Decisions\n{op_block}\n"
    )
    summary_path = out_dir / "_summary.md"
    summary_path.write_text(md, encoding="utf-8")
    return summary_path


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--file",     default=None)
    parser.add_argument("--dry-run",  action="store_true")
    args = parser.parse_args()

    source = Path(args.file) if args.file else latest_issues_file()
    print(f"[patch_writer] Source: {source.name}")

    data   = json.loads(source.read_text(encoding="utf-8"))
    issues = data.get("issues", [])

    if not issues:
        print("[patch_writer] No issues found.")
        return

    print(f"[patch_writer] {len(issues)} issue(s) found:\n")
    for i, iss in enumerate(issues, 1):
        itype = iss.get("issue_type", "MISSING — run review to regenerate")
        print(f"  {i:02d}. [{itype:20s}] {iss.get('issue','?')}")
    print()

    if args.dry_run:
        print("[patch_writer] --dry-run: no files written.")
        return

    ts      = datetime.now().strftime("%Y-%m-%d_%H%M")
    out_dir = PATCHES_DIR / ts
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"[patch_writer] Output: {out_dir}\n")

    results = []
    for i, iss in enumerate(issues, 1):
        itype   = iss.get("issue_type", "")
        node    = iss.get("node", "unknown")
        section = iss.get("section", "unknown")
        print(f"  [{i:02d}] {itype} — {iss.get('issue','?')[:60]}")

        if itype in ("code_patch", "prompt_patch"):
            ctx  = extract_file_context(node, section)
            path = generate_patch_script(iss, ctx, out_dir, i)
            print(f"       → {path.name}")
            results.append(path.name)
        elif itype == "config_change":
            ctx  = extract_file_context(node, section)
            path = generate_config_note(iss, ctx, out_dir, i)
            print(f"       → {path.name}")
            results.append(path.name)
        elif itype == "operator_decision":
            print(f"       → operator_decision (summary only)")
            results.append("operator_decision")
        else:
            print(f"       → SKIPPED (unknown type: '{itype}')")
            results.append(f"SKIPPED")

    summary = build_summary(issues, results, source, out_dir)
    print(f"\n[patch_writer] Summary → {summary}")
    actionable = sum(1 for r in results if r not in ("operator_decision",) and "SKIP" not in r)
    print(f"[patch_writer] Done — {actionable} file(s) written.")


if __name__ == "__main__":
    main()
